### ISSUE TITLE
Throwing VerifyError in < API 21

### ISSUE THREAD

**Issue by devharis** [konmik/nucleus#144]
Hello, I've recently got this error when using API 21 and lower.

```
java.lang.VerifyError: nucleus/presenter/RxPresenter
at java.lang.Class.newInstanceImpl(Native Method)
at java.lang.Class.newInstance(Class.java:1208)
at nucleus.factory.ReflectionPresenterFactory.createPresenter(ReflectionPresenterFactory.java:39)
at nucleus.view.PresenterLifecycleDelegate.getPresenter(PresenterLifecycleDelegate.java:57)
at nucleus.view.PresenterLifecycleDelegate.onResume(PresenterLifecycleDelegate.java:96)
at nucleus.view.NucleusSupportFragment.onResume(NucleusSupportFragment.java:68)
at android.support.v4.app.Fragment.performResume(Fragment.java:2238)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1346)
at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528) at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2914)
at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:509)
at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
at android.app.Activity.performResume(Activity.java:5323)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2778)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2817)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
at android.app.ActivityThread.access$800(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5017)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
at dalvik.system.NativeStart.main(Native Method)
```

Any clue on how to solve this?

**Comment by devharis** [comment]
It was nothing to do with Nucleus. I used `multiDexEnabled true` and on API <19 it didn't work without `Multidex.Install(this)`.
